language: csharp
solution: IntegrationEngine.sln

sudo: false
cache: apt

script:
  - xbuild /p:Configuration=Release IntegrationEngine.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IntegrationEngine.Model.Tests/bin/Release/IntegrationEngine.Model.Tests.dll
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IntegrationEngine.Core.Tests/bin/Release/IntegrationEngine.Core.Tests.dll
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IntegrationEngine.Tests/bin/Release/IntegrationEngine.Tests.dll
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe ./IntegrationEngine.Client.Tests/bin/Release/IntegrationEngine.Client.Tests.dll

